### PR TITLE
fix: crash when selecting new theme/color

### LINKED ISSUE #1600: 切换主题时崩了
### 摘要 / Summary

--------- Device Info
OS Version: 5.10.209-android12-9-g8879324955df (9.0.0.132SP2CHNC00E132R8P5)
OS API Level: 35
Tags: release-keys
Screen Size: 1122 x 2342
Screen Density: 2.98125
Screen orientation: Portrait
--------- Build Info
Package Name: com.osfans.trime
Builder: Nightly CI
Version Code: 20250301
Version Name: nightly-7-g8e8f8d36-release
Build Time: 2025-02-20T16:07:17Z
Build Git Hash: 8e8f8d36d6c1e012d2173c0ee9643a30f4c3e29c
--------- Crash stacktrace
androidx.startup.StartupException: lateinit property _activeTheme has not been initialized
	at com.osfans.trime.data.theme.ThemeManager.getActiveTheme(SourceFile:8)
	at com.osfans.trime.ime.core.TrimeInputMethodService.onCreateInputView(SourceFile:11)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2879)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:3828)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:3730)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:1406)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:1366)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:118)
	at android.os.Looper.loopOnce(Looper.java:237)
	at android.os.Looper.loop(Looper.java:325)
	at android.app.ActivityThread.main(ActivityThread.java:10279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

### 重现步骤 / Steps to Reproduce

切换主题

### 预期行为 / Expected Behavior

别崩

### 日志 / Log

_No response_

### 截图 / Screenshot

_No response_

### 附加信息 / Additional Context

_No response_

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

夜版

### 构建信息 / Build Information

夜版

### PR DESCRIPTION
**Pull request by MULE-FEHU-EOLIA-ARTONELICO**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1600
Fixes #

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

File: app/src/main/java/com/osfans/trime/ime/bar/ui/ToolButton.kt [hunk 1]
```diff
@@ -38,7 +38,7 @@ class ToolButton(
     ) : this(context) {
         image.imageTintList = ColorStateList.valueOf(ColorManager.getColor("comment_text_color"))
         setIcon(icon)
-        setPressHighlightColor(ColorManager.getColor("hilited_on_key_back_color"))
+        runCatching { ColorManager.getColor("hilited_on_key_back_color") }.onSuccess { setPressHighlightColor(it) }
```
Comment (WhiredPlanck) [inline app/src/main/java/com/osfans/trime/ime/bar/ui/ToolButton.kt]: 建议在 defaultFallbackColors 里给垫一个颜色

**Review by WhiredPlanck — APPROVED** [review]
