### PR TITLE
fix: crash on showing composition popup window somehow

### LINKED ISSUE #1354: Trime经常在点击输入框后迟迟无法弹出
同文输入法3.2.18（20240501）版本在真我Neo3 安卓13上经常遇到点击输入框，输入法迟迟无法弹出的情况。已经有不少人遇到这问题了，请求大佬修复下。在各个APP上都会出现这问题，而且最近的几个版本都有这问题。另外，Trime在弹出的瞬间，经常会有正在部署的提示，希望能给去掉，输入法还是瞬间加载出来好些。
image
演示视频：https://www.bilibili.com/video/BV1nr421u72S
[com.osfans.trime-2024-04-30T06_18_20Z.txt](https://github.com/osfans/trime/files/15159741/com.osfans.trime-2024-04-30T06_18_20Z.txt)
[Trime配置_240430.zip](https://github.com/osfans/trime/files/15159742/Trime._240430.zip)

### LINKED ISSUE #1356: 在输入状态下切换应用崩溃
[com.osfans.trime-2024-04-30T17_03_46Z.txt](https://github.com/osfans/trime/files/15168376/com.osfans.trime-2024-04-30T17_03_46Z.txt)

https://github.com/osfans/trime/assets/47845580/8dae7a8c-e720-4e6f-9040-9b0f4bc2fa33

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1354 (maybe)
Fixes #1356 

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

File: app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt [hunk 1]
```diff
@@ -292,27 +292,24 @@ open class TrimeInputMethodService : LifecycleInputMethodService() {
...
-            return
         }
-        mCompositionPopupWindow?.updateCompositionView()
     }
 
     /** Must be called on the UI thread
      *
      * 重置鍵盤、候選條、狀態欄等 !!注意，如果其中調用Rime.setOption，切換方案會卡住  */
     fun recreateInputView() {
-        mCompositionPopupWindow?.finishInput()
```
Comment (nopdan) [inline app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt:306]: #1260 这会导致切换夜间模式后悬浮窗无法关闭

**Comment by WhiredPlanck** [comment]
@nopdan 搞定

**Comment by Bambooin** [comment]
Both issues can't be reproduced by me with LineageOS 20.

**Review by Bambooin — APPROVED** [review]

**Review by nopdan — APPROVED** [review]
