### PR TITLE
Fix Again `KP_X` Issue

### LINKED ISSUE #1524: 使用 `KP_*` 定义的数字键盘会重复输入
### 摘要 / Summary

在 Android App 的文字方塊中，如果限制了數字類別的話，使用 Trime 的 `KP_1`, `KP_2`, etc 等作輸入，會被重覆輸入。
在其他文字方中又不會出現此問題。

### 重现步骤 / Steps to Reproduce

1. 去數字類別文字方塊 (如「質感檔案」中「新增伺服器」的「連接埠」的欄位
2. 用數字 keyboard 使用 `KP_1` 輸入
3. 會出現 "11"

### 预期行为 / Expected Behavior

只出現一個 "1"

### 日志 / Log

_No response_

### 截图 / Screenshot

_No response_

### 附加信息 / Additional Context

_No response_

### 系统版本 / OS Version

14

### 应用版本 / App Version

Latest commit version

### 构建信息 / Build Information

-

### PR DESCRIPTION
**Pull request by goofyz**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1524

#### Feature
My bad.  Previous fix in f83d28cb5f748ff5342e339566bc35bcb1a108e4 will cause `KP_X` keys not working in normal text field. 
This fix will let `KP_X` working correctly in normal & number text field.

#### Code of conduct
- [X] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [X] `make sytle-lint`
- [X] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [X] `make debug`

#### Manually test
- [X] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

File: app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt [hunk 1]
```diff
@@ -243,7 +243,13 @@ open class TrimeInputMethodService : LifecycleInputMethodService() {
                                 handleReturnKey()
                                 return
                             }
-                            sendDownKeyEvent(eventTime, keyCode, it.modifiers.metaState)
+
+                            if (keyCode in KeyEvent.KEYCODE_NUMPAD_0..KeyEvent.KEYCODE_NUMPAD_EQUALS) {
+                                // ignore KP_X keys, which is handled in `CommonKeyboardActionListener`.
```
Comment (WhiredPlanck) [inline app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt:248]: This may cause IMS cannot reponse the corresponding keyevent from physical keyboard, maybe we should tell if the keyevent is from virtual keyboard or physical keyboard. But now, let us workaround for virtual keyboard first.

**Review by WhiredPlanck — APPROVED** [review]
