### PR TITLE
Fix some liquid keyboard bugs

### LINKED ISSUE #1296: 打开液体键盘的候选标签，会先显示上一次的候选字，然后才刷新成当前候选
3.2.17，之前是正常的。
这个是我的候选键设定：
      - {click: 'liquid_keyboard_clipboard', key_text_size: 14, long_click: '',  key_symbol_offset_x: 9, has_menu: liquid_keyboard_candidate, key_back_color: bgn, key_text_color: th4}

### LINKED ISSUE #1306: 20230324每夜版 剪贴板、收藏夹、草稿箱三者之间无法互相切换
操作步骤:1.液态键盘界面，选中“剪贴板”后点击“收藏夹”和“草稿箱”的tab键不会切换过去，需要先切换到另一个tab如“emoji”，再去点击“收藏夹”或“草稿箱”才会切换，在“收藏夹”或“草稿箱”点击另两者也是同理

2.另一个bug(我感觉这两个应该有联系)在键盘里，设置一个进入“剪贴板”的按键，平时点击此按键当然是会进入剪贴板的，然而如果最后退出液态键盘时在“收藏夹”的界面，再点击该按键不会进入“剪贴板”而会进入“收藏夹”，“草稿箱”同理，如果是在其他普通的tab如“emoji”退出液态键盘，再使用该按键就是正常的

### PR DESCRIPTION
**Pull request by goofyz**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1296 
Fixes #1306
refs #1280

#### Feature
修改一些關於 liquid keyboard 的問題。

關於 #1280 ，找不到令 `span` 支援背景檔的方法，現在的修改只是令程式不崩潰而已。建議改善文檔，說明 `key_back_color` 為圖檔時，懸浮窗的按鍵背景會變回預設顏色。

#### Code of conduct
- [X] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [ ] `make sytle-lint`

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Review by Bambooin — APPROVED** [review]

File: app/src/main/java/com/osfans/trime/ime/symbol/DbAdapter.kt [hunk 1]
```diff
@@ -0,0 +1,121 @@
+package com.osfans.trime.ime.symbol
```
Comment (WhiredPlanck) [inline app/src/main/java/com/osfans/trime/ime/symbol/DbAdapter.kt:1]: 怪我这几天没关注 PR …… 刷新问题我早就修完了，但没空推送 ……
